name: Test EC2 Runner with Repo Data

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  run-commands:
    runs-on: self-hosted  # Specify the self-hosted runner (your EC2 instance)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Clones the repo onto the runner

      - name: List Files in Repo Directory
        run: ls -la  # List all files in the current directory

      - name: Show Current Directory Path
        run: pwd
