# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Deploy react

on:
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  run-commands:
    runs-on: self-hosted  # Specify the self-hosted runner (your EC2 instance)

    steps:
      - name: Run `ls` Command
        run: ls

      - name: Run `pwd` Command
        run: pwd
